"""init schema

Revision ID: 59c4946d448d
Revises:
Create Date: 2026-01-15 11:56:33.920501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59c4946d448d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("thumb", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
    ),
    sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
    sa.Column("bank", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("promotions")
    # ### end Alembic commands ###
