"""change model

Revision ID: 770bf3b60758
Revises: 59c4946d448d
Create Date: 2026-01-15 12:14:29.784995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '770bf3b60758'
down_revision: Union[str, Sequence[str], None] = '59c4946d448d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('merchant', sa.String(), nullable=False))
    op.add_column('promotions', sa.Column('card_type', sa.String(), nullable=False))
    op.add_column('promotions', sa.Column('valid_to', sa.String(), nullable=True))
    op.alter_column('promotions', 'thumb',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('promotions', 'category')
    op.drop_column('promotions', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('promotions', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('promotions', 'thumb',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('promotions', 'valid_to')
    op.drop_column('promotions', 'card_type')
    op.drop_column('promotions', 'merchant')
    # ### end Alembic commands ###
