"""init uuid schema

Revision ID: bdf029cf8009
Revises:
Create Date: 2026-01-12 10:13:47.442956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.timezone import DateTimeUTC

# revision identifiers, used by Alembic.
revision: str = "bdf029cf8009"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "promotions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("thumb", sa.String(), nullable=False),
        sa.Column("merchant", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("start_date", DateTimeUTC(timezone=True), nullable=True),
        sa.Column("end_date", DateTimeUTC(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["merchant"], ["merchant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("promotions")
    op.drop_table("merchant")
    # ### end Alembic commands ###
